#Server settings
web:
  #Address to listen
  listen: ":3000"
  debugTemplates: false

db:
  #PostgreSQL connection string
  url: "postgres://ensemble:ensemble@localhost:5432/ensemble?sslmode=disable"
  #Passwords and keys encryption secret (random string)
  secret: ""

#Directory to store project repositories
path: "data"

#Projects update schedule (cron)
update: "0 3 * * *"
