#Server settings
web:
  #Address to listen
  listen: ":3000"
  debugTemplates: false

db:
  #PostgreSQL connection string
  url: "postgres://ensemble:ensemble@localhost:5432/ensemble?sslmode=disable"
  #Passwords and keys encryption secret (random string)
  secret: ""

#Directory to store project repositories
path: "data"

keys:
  #Directory to store private keys
  path: "keys"
  #SSH_ASKPASS script
  addKeyScript: "./ssh_add_key.sh"
  #Override SSH_AUTH_SOCK of ssh-agent
  authSock: ""

#Projects update schedule (cron)
update: "0 3 * * *"
